### PR TITLE
[WASM] migrate to package:web and dart:js_interop

### PR DESCRIPTION
**Pull request by hnvn**
In order to [support web assembly](https://docs.flutter.dev/platform-integration/web/wasm), the package need to be migrated to `package:web` and `dart:js_interop` instead of `dart:html` and `package:js`

### CODE REVIEW

**Comment by hnvn** [comment]
@jerson can you have a look?

**Comment by jerson** [comment]
@hnvn thank you very much for this PR, yeah sure gonna take a look this weekend, im AFK these days

**Comment by hnvn** [comment]
@jerson do you have plan to release new package version for this PR?

**Comment by jerson** [comment]
yeah the github pipeline was failing, here is the new version: https://pub.dev/packages/fast_rsa/versions/3.6.4

**Pull request merged**
